apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: pgbouncer
spec:
  replicas: 4
  selector:
    matchLabels:
      name: pgbouncer
  template:
    metadata:
      labels:
        name: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: azsenaprdcrpgbouncer.azurecr.io/sena-pgbouncer:1.22.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pgbouncer-config
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 30
          periodSeconds: 5
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      - key: "workload-type"
        operator: "Equal"
        value: "pgbouncer"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: pgbouncerp01